# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Browser Domain Events"""

from pydantic import BaseModel
from typing import Optional

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..page.types import FrameId

class DownloadWillBeginEvent(BaseModel):
    """Fired when page is about to start a download."""
    frameId: "FrameId"
    guid: "str"
    url: "str"
    suggestedFilename: "str"



class DownloadProgressEvent(BaseModel):
    """Fired when download makes progress. Last call has |done| == true."""
    guid: "str"
    totalBytes: "float"
    receivedBytes: "float"
    state: "str"
    filePath: "Optional[str]" = None


# Rebuild Pydantic models to resolve forward references
def _rebuild_models_when_ready():
    try:
        from ..page.types import FrameId
        # Rebuild models now that imports are available
        DownloadWillBeginEvent.model_rebuild()
        DownloadProgressEvent.model_rebuild()
    except ImportError:
        pass  # Will be rebuilt later

_rebuild_models_when_ready()
