# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Extensions Domain Commands"""

from pydantic import BaseModel
from typing import Any, Dict, List, Optional
from typing_extensions import TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .types import StorageArea

class LoadUnpackedParameters(TypedDict):
    path: "str"
    """Absolute file path."""


class LoadUnpackedReturns(BaseModel):
    id: "str"



class UninstallParameters(TypedDict):
    id: "str"
    """Extension id."""





class GetStorageItemsParameters(TypedDict):
    id: "str"
    """ID of extension."""
    storageArea: "StorageArea"
    """StorageArea to retrieve data from."""
    keys: "Optional[List[str]]"
    """Keys to retrieve."""


class GetStorageItemsReturns(BaseModel):
    data: "Dict[str, Any]"



class RemoveStorageItemsParameters(TypedDict):
    id: "str"
    """ID of extension."""
    storageArea: "StorageArea"
    """StorageArea to remove data from."""
    keys: "List[str]"
    """Keys to remove."""





class ClearStorageItemsParameters(TypedDict):
    id: "str"
    """ID of extension."""
    storageArea: "StorageArea"
    """StorageArea to remove data from."""





class SetStorageItemsParameters(TypedDict):
    id: "str"
    """ID of extension."""
    storageArea: "StorageArea"
    """StorageArea to set data in."""
    values: "Dict[str, Any]"
    """Values to set."""




# Rebuild Pydantic models to resolve forward references
def _rebuild_models_when_ready():
    try:
        from .types import StorageArea
        # Rebuild models now that imports are available
        LoadUnpackedReturns.model_rebuild()
        GetStorageItemsReturns.model_rebuild()
    except ImportError:
        pass  # Will be rebuilt later

_rebuild_models_when_ready()
