# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Extensions Domain Types"""

from typing import Any, Dict, List, Optional, Union
from typing_extensions import Literal
from typing_extensions import NotRequired, TypedDict

StorageArea = Literal["session", "local", "sync", "managed"]
"""Storage areas."""
