# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP HeadlessExperimental Domain Types"""

from pydantic import BaseModel
from typing import Optional

class ScreenshotParams(BaseModel):
    """Encoding options for a screenshot."""
    format: "Optional[str]" = None
    quality: "Optional[int]" = None
    optimizeForSpeed: "Optional[bool]" = None


# Rebuild Pydantic models to resolve forward references
# Import dependencies for model rebuilding
def _rebuild_models_when_ready():
    try:
        # Rebuild models now that imports are available
        ScreenshotParams.model_rebuild()
    except ImportError:
        pass  # Will be rebuilt later

_rebuild_models_when_ready()
