# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP BackgroundService Domain Events"""

from pydantic import BaseModel

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .types import BackgroundServiceEvent
    from .types import ServiceName

class RecordingStateChangedEvent(BaseModel):
    """Called when the recording state for the service has been updated."""
    isRecording: "bool"
    service: "ServiceName"



class BackgroundServiceEventReceivedEvent(BaseModel):
    """Called with all existing backgroundServiceEvents when enabled, and all new
events afterwards if enabled and recording."""
    backgroundServiceEvent: "BackgroundServiceEvent"


# Rebuild Pydantic models to resolve forward references
def _rebuild_models_when_ready():
    try:
        from .types import BackgroundServiceEvent
        from .types import ServiceName
        # Rebuild models now that imports are available
        RecordingStateChangedEvent.model_rebuild()
        BackgroundServiceEventReceivedEvent.model_rebuild()
    except ImportError:
        pass  # Will be rebuilt later

_rebuild_models_when_ready()
