# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP DOM Domain Event Registration"""

from typing import Callable, Optional, Protocol

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..registry import EventRegistry
    from .events import *

class DOMRegistration:
    """Event registration interface for DOM domain."""

    def __init__(self, registry: 'EventRegistry'):
        self._registry = registry
        self._domain = "DOM"

    def attribute_modified(
        self,
        callback: Callable[['AttributeModifiedEvent', Optional[str]], None],
    ) -> None:
        """
        Register a callback for attributeModified events.
        
        Fired when `Element`'s attribute is modified.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("DOM.attributeModified", callback)

    def attribute_removed(
        self,
        callback: Callable[['AttributeRemovedEvent', Optional[str]], None],
    ) -> None:
        """
        Register a callback for attributeRemoved events.
        
        Fired when `Element`'s attribute is removed.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("DOM.attributeRemoved", callback)

    def character_data_modified(
        self,
        callback: Callable[['CharacterDataModifiedEvent', Optional[str]], None],
    ) -> None:
        """
        Register a callback for characterDataModified events.
        
        Mirrors `DOMCharacterDataModified` event.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("DOM.characterDataModified", callback)

    def child_node_count_updated(
        self,
        callback: Callable[['ChildNodeCountUpdatedEvent', Optional[str]], None],
    ) -> None:
        """
        Register a callback for childNodeCountUpdated events.
        
        Fired when `Container`'s child node count has changed.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("DOM.childNodeCountUpdated", callback)

    def child_node_inserted(
        self,
        callback: Callable[['ChildNodeInsertedEvent', Optional[str]], None],
    ) -> None:
        """
        Register a callback for childNodeInserted events.
        
        Mirrors `DOMNodeInserted` event.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("DOM.childNodeInserted", callback)

    def child_node_removed(
        self,
        callback: Callable[['ChildNodeRemovedEvent', Optional[str]], None],
    ) -> None:
        """
        Register a callback for childNodeRemoved events.
        
        Mirrors `DOMNodeRemoved` event.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("DOM.childNodeRemoved", callback)

    def distributed_nodes_updated(
        self,
        callback: Callable[['DistributedNodesUpdatedEvent', Optional[str]], None],
    ) -> None:
        """
        Register a callback for distributedNodesUpdated events.
        
        Called when distribution is changed.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("DOM.distributedNodesUpdated", callback)

    def document_updated(
        self,
        callback: Callable[['DocumentUpdatedEvent', Optional[str]], None],
    ) -> None:
        """
        Register a callback for documentUpdated events.
        
        Fired when `Document` has been totally updated. Node ids are no longer valid.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("DOM.documentUpdated", callback)

    def inline_style_invalidated(
        self,
        callback: Callable[['InlineStyleInvalidatedEvent', Optional[str]], None],
    ) -> None:
        """
        Register a callback for inlineStyleInvalidated events.
        
        Fired when `Element`'s inline style is modified via a CSS property modification.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("DOM.inlineStyleInvalidated", callback)

    def pseudo_element_added(
        self,
        callback: Callable[['PseudoElementAddedEvent', Optional[str]], None],
    ) -> None:
        """
        Register a callback for pseudoElementAdded events.
        
        Called when a pseudo element is added to an element.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("DOM.pseudoElementAdded", callback)

    def top_layer_elements_updated(
        self,
        callback: Callable[['TopLayerElementsUpdatedEvent', Optional[str]], None],
    ) -> None:
        """
        Register a callback for topLayerElementsUpdated events.
        
        Called when top layer elements are changed.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("DOM.topLayerElementsUpdated", callback)

    def scrollable_flag_updated(
        self,
        callback: Callable[['ScrollableFlagUpdatedEvent', Optional[str]], None],
    ) -> None:
        """
        Register a callback for scrollableFlagUpdated events.
        
        Fired when a node's scrollability state changes.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("DOM.scrollableFlagUpdated", callback)

    def pseudo_element_removed(
        self,
        callback: Callable[['PseudoElementRemovedEvent', Optional[str]], None],
    ) -> None:
        """
        Register a callback for pseudoElementRemoved events.
        
        Called when a pseudo element is removed from an element.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("DOM.pseudoElementRemoved", callback)

    def set_child_nodes(
        self,
        callback: Callable[['SetChildNodesEvent', Optional[str]], None],
    ) -> None:
        """
        Register a callback for setChildNodes events.
        
        Fired when backend wants to provide client with the missing DOM structure. This happens upon
most of the calls requesting node ids.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("DOM.setChildNodes", callback)

    def shadow_root_popped(
        self,
        callback: Callable[['ShadowRootPoppedEvent', Optional[str]], None],
    ) -> None:
        """
        Register a callback for shadowRootPopped events.
        
        Called when shadow root is popped from the element.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("DOM.shadowRootPopped", callback)

    def shadow_root_pushed(
        self,
        callback: Callable[['ShadowRootPushedEvent', Optional[str]], None],
    ) -> None:
        """
        Register a callback for shadowRootPushed events.
        
        Called when shadow root is pushed into the element.
        
        Args:
            callback: Function to call when event occurs.
                     Receives (event_data, session_id) as parameters.
        """
        self._registry.register("DOM.shadowRootPushed", callback)

