# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Animation Domain Commands"""

from pydantic import BaseModel
from typing import List
from typing_extensions import TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..runtime.types import RemoteObject

class GetCurrentTimeParameters(TypedDict):
    id: "str"


class GetCurrentTimeReturns(BaseModel):
    currentTime: "float"



class GetPlaybackRateReturns(BaseModel):
    playbackRate: "float"



class ReleaseAnimationsParameters(TypedDict):
    animations: "List[str]"





class ResolveAnimationParameters(TypedDict):
    animationId: "str"


class ResolveAnimationReturns(BaseModel):
    remoteObject: "RemoteObject"



class SeekAnimationsParameters(TypedDict):
    animations: "List[str]"
    currentTime: "float"





class SetPausedParameters(TypedDict):
    animations: "List[str]"
    paused: "bool"





class SetPlaybackRateParameters(TypedDict):
    playbackRate: "float"





class SetTimingParameters(TypedDict):
    animationId: "str"
    duration: "float"
    delay: "float"




# Rebuild Pydantic models to resolve forward references
def _rebuild_models_when_ready():
    try:
        from ..runtime.types import RemoteObject
        # Rebuild models now that imports are available
        GetCurrentTimeReturns.model_rebuild()
        GetPlaybackRateReturns.model_rebuild()
        ResolveAnimationReturns.model_rebuild()
    except ImportError:
        pass  # Will be rebuilt later

_rebuild_models_when_ready()
