# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Animation Domain Events"""

from pydantic import BaseModel

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .types import Animation

class AnimationCanceledEvent(BaseModel):
    """Event for when an animation has been cancelled."""
    id: "str"



class AnimationCreatedEvent(BaseModel):
    """Event for each animation that has been created."""
    id: "str"



class AnimationStartedEvent(BaseModel):
    """Event for animation that has been started."""
    animation: "Animation"



class AnimationUpdatedEvent(BaseModel):
    """Event for animation that has been updated."""
    animation: "Animation"


# Rebuild Pydantic models to resolve forward references
def _rebuild_models_when_ready():
    try:
        from .types import Animation
        # Rebuild models now that imports are available
        AnimationCanceledEvent.model_rebuild()
        AnimationCreatedEvent.model_rebuild()
        AnimationStartedEvent.model_rebuild()
        AnimationUpdatedEvent.model_rebuild()
    except ImportError:
        pass  # Will be rebuilt later

_rebuild_models_when_ready()
