# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Performance Domain Commands"""

from pydantic import BaseModel
from typing import List
from typing_extensions import TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .types import Metric

class EnableParameters(TypedDict, total=False):
    timeDomain: "str"
    """Time domain to use for collecting and reporting duration metrics."""





class SetTimeDomainParameters(TypedDict):
    timeDomain: "str"
    """Time domain"""





class GetMetricsReturns(BaseModel):
    metrics: "List[Metric]"


# Rebuild Pydantic models to resolve forward references
def _rebuild_models_when_ready():
    try:
        from .types import Metric
        # Rebuild models now that imports are available
        GetMetricsReturns.model_rebuild()
    except ImportError:
        pass  # Will be rebuilt later

_rebuild_models_when_ready()
