# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Autofill Domain Events"""

from pydantic import BaseModel
from typing import List

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .types import AddressUI
    from .types import FilledField

class AddressFormFilledEvent(BaseModel):
    """Emitted when an address form is filled."""
    filledFields: "List[FilledField]"
    addressUi: "AddressUI"


# Rebuild Pydantic models to resolve forward references
def _rebuild_models_when_ready():
    try:
        from .types import AddressUI
        from .types import FilledField
        # Rebuild models now that imports are available
        AddressFormFilledEvent.model_rebuild()
    except ImportError:
        pass  # Will be rebuilt later

_rebuild_models_when_ready()
