# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Accessibility Domain Commands"""

from pydantic import BaseModel
from typing import List
from typing_extensions import TypedDict, NotRequired

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..dom.types import BackendNodeId
    from ..dom.types import NodeId
    from ..page.types import FrameId
    from ..runtime.types import RemoteObjectId
    from .types import AXNode
    from .types import AXNodeId

class GetPartialAXTreeParameters(TypedDict, total=False):
    nodeId: "NodeId"
    backendNodeId: "BackendNodeId"
    objectId: "RemoteObjectId"
    fetchRelatives: "bool"


class GetPartialAXTreeReturns(BaseModel):
    nodes: "List[AXNode]"



class GetFullAXTreeParameters(TypedDict, total=False):
    depth: "int"
    frameId: "FrameId"


class GetFullAXTreeReturns(BaseModel):
    nodes: "List[AXNode]"



class GetRootAXNodeParameters(TypedDict, total=False):
    frameId: "FrameId"


class GetRootAXNodeReturns(BaseModel):
    node: "AXNode"



class GetAXNodeAndAncestorsParameters(TypedDict, total=False):
    nodeId: "NodeId"
    backendNodeId: "BackendNodeId"
    objectId: "RemoteObjectId"


class GetAXNodeAndAncestorsReturns(BaseModel):
    nodes: "List[AXNode]"



class GetChildAXNodesParameters(TypedDict):
    id: "AXNodeId"
    frameId: "NotRequired[FrameId]"


class GetChildAXNodesReturns(BaseModel):
    nodes: "List[AXNode]"



class QueryAXTreeParameters(TypedDict, total=False):
    nodeId: "NodeId"
    backendNodeId: "BackendNodeId"
    objectId: "RemoteObjectId"
    accessibleName: "str"
    role: "str"


class QueryAXTreeReturns(BaseModel):
    nodes: "List[AXNode]"


# Rebuild Pydantic models to resolve forward references
def _rebuild_models_when_ready():
    try:
        from ..dom.types import BackendNodeId
        from ..dom.types import NodeId
        from ..page.types import FrameId
        from ..runtime.types import RemoteObjectId
        from .types import AXNode
        from .types import AXNodeId
        # Rebuild models now that imports are available
        GetPartialAXTreeReturns.model_rebuild()
        GetFullAXTreeReturns.model_rebuild()
        GetRootAXNodeReturns.model_rebuild()
        GetAXNodeAndAncestorsReturns.model_rebuild()
        GetChildAXNodesReturns.model_rebuild()
        QueryAXTreeReturns.model_rebuild()
    except ImportError:
        pass  # Will be rebuilt later

_rebuild_models_when_ready()
