# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Input Domain Events"""

from pydantic import BaseModel

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .types import DragData

class DragInterceptedEvent(BaseModel):
    """Emitted only when `Input.setInterceptDrags` is enabled. Use this data with `Input.dispatchDragEvent` to
restore normal drag and drop behavior."""
    data: "DragData"


# Rebuild Pydantic models to resolve forward references
def _rebuild_models_when_ready():
    try:
        from .types import DragData
        # Rebuild models now that imports are available
        DragInterceptedEvent.model_rebuild()
    except ImportError:
        pass  # Will be rebuilt later

_rebuild_models_when_ready()
