# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Input Domain Types"""

from enum import Enum
from pydantic import BaseModel
from typing import List, Optional

class TouchPoint(BaseModel):
    x: "float"
    y: "float"
    radiusX: "Optional[float]" = None
    radiusY: "Optional[float]" = None
    rotationAngle: "Optional[float]" = None
    force: "Optional[float]" = None
    tangentialPressure: "Optional[float]" = None
    tiltX: "Optional[float]" = None
    tiltY: "Optional[float]" = None
    twist: "Optional[int]" = None
    id: "Optional[float]" = None



class GestureSourceType(Enum):
    DEFAULT = "default"
    TOUCH = "touch"
    MOUSE = "mouse"



class MouseButton(Enum):
    NONE = "none"
    LEFT = "left"
    MIDDLE = "middle"
    RIGHT = "right"
    BACK = "back"
    FORWARD = "forward"



"""UTC time in seconds, counted from January 1, 1970."""
TimeSinceEpoch = float



class DragDataItem(BaseModel):
    mimeType: "str"
    data: "str"
    title: "Optional[str]" = None
    baseURL: "Optional[str]" = None



class DragData(BaseModel):
    items: "List[DragDataItem]"
    dragOperationsMask: "int"
    files: "Optional[List[str]]" = None


# Rebuild Pydantic models to resolve forward references
# Import dependencies for model rebuilding
def _rebuild_models_when_ready():
    try:
        # Rebuild models now that imports are available
        TouchPoint.model_rebuild()
        DragDataItem.model_rebuild()
        DragData.model_rebuild()
    except ImportError:
        pass  # Will be rebuilt later

_rebuild_models_when_ready()
