# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP PWA Domain Commands"""

from pydantic import BaseModel
from typing import List, Union
from typing_extensions import TypedDict, NotRequired

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..target.types import TargetID
    from .types import DisplayMode
    from .types import FileHandler

class GetOsAppStateParameters(TypedDict):
    manifestId: "str"


class GetOsAppStateReturns(BaseModel):
    badgeCount: "int"
    fileHandlers: "List[FileHandler]"



class InstallParameters(TypedDict):
    manifestId: "str"
    installUrlOrBundleUrl: "NotRequired[str]"





class UninstallParameters(TypedDict):
    manifestId: "str"





class LaunchParameters(TypedDict):
    manifestId: "str"
    url: "NotRequired[str]"


class LaunchReturns(BaseModel):
    targetId: "TargetID"



class LaunchFilesInAppParameters(TypedDict):
    manifestId: "str"
    files: "List[str]"


class LaunchFilesInAppReturns(BaseModel):
    targetIds: "List[TargetID]"



class OpenCurrentPageInAppParameters(TypedDict):
    manifestId: "str"





class ChangeAppUserSettingsParameters(TypedDict):
    manifestId: "str"
    linkCapturing: "NotRequired[bool]"
    displayMode: "NotRequired[Union[DisplayMode, str]]"




# Rebuild Pydantic models to resolve forward references
def _rebuild_models_when_ready():
    try:
        from ..target.types import TargetID
        from .types import DisplayMode
        from .types import FileHandler
        # Rebuild models now that imports are available
        GetOsAppStateReturns.model_rebuild()
        LaunchReturns.model_rebuild()
        LaunchFilesInAppReturns.model_rebuild()
    except ImportError:
        pass  # Will be rebuilt later

_rebuild_models_when_ready()
