# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Media Domain Events"""

from pydantic import BaseModel
from typing import List

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .types import PlayerError
    from .types import PlayerEvent
    from .types import PlayerId
    from .types import PlayerMessage
    from .types import PlayerProperty

class PlayerPropertiesChangedEvent(BaseModel):
    """This can be called multiple times, and can be used to set / override /
remove player properties. A null propValue indicates removal."""
    playerId: "PlayerId"
    properties: "List[PlayerProperty]"



class PlayerEventsAddedEvent(BaseModel):
    """Send events as a list, allowing them to be batched on the browser for less
congestion. If batched, events must ALWAYS be in chronological order."""
    playerId: "PlayerId"
    events: "List[PlayerEvent]"



class PlayerMessagesLoggedEvent(BaseModel):
    """Send a list of any messages that need to be delivered."""
    playerId: "PlayerId"
    messages: "List[PlayerMessage]"



class PlayerErrorsRaisedEvent(BaseModel):
    """Send a list of any errors that need to be delivered."""
    playerId: "PlayerId"
    errors: "List[PlayerError]"



class PlayersCreatedEvent(BaseModel):
    """Called whenever a player is created, or when a new agent joins and receives
a list of active players. If an agent is restored, it will receive the full
list of player ids and all events again."""
    players: "List[PlayerId]"


# Rebuild Pydantic models to resolve forward references
def _rebuild_models_when_ready():
    try:
        from .types import PlayerError
        from .types import PlayerEvent
        from .types import PlayerId
        from .types import PlayerMessage
        from .types import PlayerProperty
        # Rebuild models now that imports are available
        PlayerPropertiesChangedEvent.model_rebuild()
        PlayerEventsAddedEvent.model_rebuild()
        PlayerMessagesLoggedEvent.model_rebuild()
        PlayerErrorsRaisedEvent.model_rebuild()
        PlayersCreatedEvent.model_rebuild()
    except ImportError:
        pass  # Will be rebuilt later

_rebuild_models_when_ready()
