# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP DeviceAccess Domain Events"""

from pydantic import BaseModel
from typing import List

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .types import PromptDevice
    from .types import RequestId

class DeviceRequestPromptedEvent(BaseModel):
    """A device request opened a user prompt to select a device. Respond with the
selectPrompt or cancelPrompt command."""
    id: "RequestId"
    devices: "List[PromptDevice]"


# Rebuild Pydantic models to resolve forward references
def _rebuild_models_when_ready():
    try:
        from .types import PromptDevice
        from .types import RequestId
        # Rebuild models now that imports are available
        DeviceRequestPromptedEvent.model_rebuild()
    except ImportError:
        pass  # Will be rebuilt later

_rebuild_models_when_ready()
