# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Schema Domain Library"""

from typing import Any, Dict, Optional

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ...client import CDPClient
    from .commands import GetDomainsReturns

class SchemaClient:
    """Client for Schema domain commands."""

    def __init__(self, client: 'CDPClient'):
        self._client = client

    async def getDomains(
        self,
        params: None = None,
        session_id: Optional[str] = None,
    ) -> "GetDomainsReturns":
        """Returns supported domains."""
        raw_result: Dict[str, Any] = await self._client.send_raw(
            method="Schema.getDomains",
            params=params,
            session_id=session_id,
        )
        from .commands import GetDomainsReturns as _GetDomainsReturns
        return _GetDomainsReturns.model_validate(raw_result)


