# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP DOMStorage Domain Types"""

from pydantic import BaseModel
from typing import List, Optional

SerializedStorageKey = str



class StorageId(BaseModel):
    """DOM Storage identifier."""
    isLocalStorage: "bool"
    securityOrigin: "Optional[str]" = None
    storageKey: "Optional[SerializedStorageKey]" = None



"""DOM Storage item."""
Item = List[str]


# Rebuild Pydantic models to resolve forward references
# Import dependencies for model rebuilding
def _rebuild_models_when_ready():
    try:
        # Rebuild models now that imports are available
        StorageId.model_rebuild()
    except ImportError:
        pass  # Will be rebuilt later

_rebuild_models_when_ready()
