# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Emulation Domain Events"""

from pydantic import BaseModel

class VirtualTimeBudgetExpiredEvent(BaseModel):
    """Notification sent after the virtual time budget for the current VirtualTimePolicy has run out."""
    pass


# Rebuild Pydantic models to resolve forward references
def _rebuild_models_when_ready():
    try:
        # Rebuild models now that imports are available
        VirtualTimeBudgetExpiredEvent.model_rebuild()
    except ImportError:
        pass  # Will be rebuilt later

_rebuild_models_when_ready()
