# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP Memory Domain Commands"""

from pydantic import BaseModel
from typing import List
from typing_extensions import TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .types import DOMCounter
    from .types import PressureLevel
    from .types import SamplingProfile

class GetDOMCountersReturns(BaseModel):
    documents: "int"
    nodes: "int"
    jsEventListeners: "int"



class GetDOMCountersForLeakDetectionReturns(BaseModel):
    counters: "List[DOMCounter]"



class SetPressureNotificationsSuppressedParameters(TypedDict):
    suppressed: "bool"
    """If true, memory pressure notifications will be suppressed."""





class SimulatePressureNotificationParameters(TypedDict):
    level: "PressureLevel"
    """Memory pressure level of the notification."""





class StartSamplingParameters(TypedDict, total=False):
    samplingInterval: "int"
    """Average number of bytes between samples."""
    suppressRandomness: "bool"
    """Do not randomize intervals between samples."""





class GetAllTimeSamplingProfileReturns(BaseModel):
    profile: "SamplingProfile"



class GetBrowserSamplingProfileReturns(BaseModel):
    profile: "SamplingProfile"



class GetSamplingProfileReturns(BaseModel):
    profile: "SamplingProfile"


# Rebuild Pydantic models to resolve forward references
def _rebuild_models_when_ready():
    try:
        from .types import DOMCounter
        from .types import PressureLevel
        from .types import SamplingProfile
        # Rebuild models now that imports are available
        GetDOMCountersReturns.model_rebuild()
        GetDOMCountersForLeakDetectionReturns.model_rebuild()
        GetAllTimeSamplingProfileReturns.model_rebuild()
        GetBrowserSamplingProfileReturns.model_rebuild()
        GetSamplingProfileReturns.model_rebuild()
    except ImportError:
        pass  # Will be rebuilt later

_rebuild_models_when_ready()
