# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP LayerTree Domain Commands"""

from pydantic import BaseModel
from typing import Any, Dict, List, Optional
from typing_extensions import TypedDict

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..dom.types import Rect
    from .types import LayerId
    from .types import PaintProfile
    from .types import PictureTile
    from .types import SnapshotId

class CompositingReasonsParameters(TypedDict):
    layerId: "LayerId"
    """The id of the layer for which we want to get the reasons it was composited."""


class CompositingReasonsReturns(BaseModel):
    compositingReasons: "List[str]"
    compositingReasonIds: "List[str]"



class LoadSnapshotParameters(TypedDict):
    tiles: "List[PictureTile]"
    """An array of tiles composing the snapshot."""


class LoadSnapshotReturns(BaseModel):
    snapshotId: "SnapshotId"



class MakeSnapshotParameters(TypedDict):
    layerId: "LayerId"
    """The id of the layer."""


class MakeSnapshotReturns(BaseModel):
    snapshotId: "SnapshotId"



class ProfileSnapshotParameters(TypedDict):
    snapshotId: "SnapshotId"
    """The id of the layer snapshot."""
    minRepeatCount: "Optional[int]"
    """The maximum number of times to replay the snapshot (1, if not specified)."""
    minDuration: "Optional[float]"
    """The minimum duration (in seconds) to replay the snapshot."""
    clipRect: "Optional[Rect]"
    """The clip rectangle to apply when replaying the snapshot."""


class ProfileSnapshotReturns(BaseModel):
    timings: "List[PaintProfile]"



class ReleaseSnapshotParameters(TypedDict):
    snapshotId: "SnapshotId"
    """The id of the layer snapshot."""





class ReplaySnapshotParameters(TypedDict):
    snapshotId: "SnapshotId"
    """The id of the layer snapshot."""
    fromStep: "Optional[int]"
    """The first step to replay from (replay from the very start if not specified)."""
    toStep: "Optional[int]"
    """The last step to replay to (replay till the end if not specified)."""
    scale: "Optional[float]"
    """The scale to apply while replaying (defaults to 1)."""


class ReplaySnapshotReturns(BaseModel):
    dataURL: "str"



class SnapshotCommandLogParameters(TypedDict):
    snapshotId: "SnapshotId"
    """The id of the layer snapshot."""


class SnapshotCommandLogReturns(BaseModel):
    commandLog: "List[Dict[str, Any]]"


# Rebuild Pydantic models to resolve forward references
def _rebuild_models_when_ready():
    try:
        from ..dom.types import Rect
        from .types import LayerId
        from .types import PaintProfile
        from .types import PictureTile
        from .types import SnapshotId
        # Rebuild models now that imports are available
        CompositingReasonsReturns.model_rebuild()
        LoadSnapshotReturns.model_rebuild()
        MakeSnapshotReturns.model_rebuild()
        ProfileSnapshotReturns.model_rebuild()
        ReplaySnapshotReturns.model_rebuild()
        SnapshotCommandLogReturns.model_rebuild()
    except ImportError:
        pass  # Will be rebuilt later

_rebuild_models_when_ready()
