# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP FedCm Domain Events"""

from pydantic import BaseModel
from typing import List, Optional, Union

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .types import Account
    from .types import DialogType

class DialogShownEvent(BaseModel):
    dialogId: "str"
    dialogType: "Union[DialogType, str]"
    accounts: "List[Account]"
    title: "str"
    subtitle: "Optional[str]" = None



class DialogClosedEvent(BaseModel):
    """Triggered when a dialog is closed, either by user action, JS abort,
or a command below."""
    dialogId: "str"


# Rebuild Pydantic models to resolve forward references
def _rebuild_models_when_ready():
    try:
        from .types import Account
        from .types import DialogType
        # Rebuild models now that imports are available
        DialogShownEvent.model_rebuild()
        DialogClosedEvent.model_rebuild()
    except ImportError:
        pass  # Will be rebuilt later

_rebuild_models_when_ready()
