# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP FedCm Domain Types"""

from enum import Enum
from pydantic import BaseModel
from typing import Optional, Union

class LoginState(Enum):
    """Whether this is a sign-up or sign-in action for this account, i.e.
whether this account has ever been used to sign in to this RP before."""
    SIGNIN = "SignIn"
    SIGNUP = "SignUp"



class DialogType(Enum):
    """The types of FedCM dialogs."""
    ACCOUNTCHOOSER = "AccountChooser"
    AUTOREAUTHN = "AutoReauthn"
    CONFIRMIDPLOGIN = "ConfirmIdpLogin"
    ERROR = "Error"



class DialogButton(Enum):
    """The buttons on the FedCM dialog."""
    CONFIRMIDPLOGINCONTINUE = "ConfirmIdpLoginContinue"
    ERRORGOTIT = "ErrorGotIt"
    ERRORMOREDETAILS = "ErrorMoreDetails"



class AccountUrlType(Enum):
    """The URLs that each account has"""
    TERMSOFSERVICE = "TermsOfService"
    PRIVACYPOLICY = "PrivacyPolicy"



class Account(BaseModel):
    """Corresponds to IdentityRequestAccount"""
    accountId: "str"
    email: "str"
    name: "str"
    givenName: "str"
    pictureUrl: "str"
    idpConfigUrl: "str"
    idpLoginUrl: "str"
    loginState: "Union[LoginState, str]"
    termsOfServiceUrl: "Optional[str]" = None
    privacyPolicyUrl: "Optional[str]" = None


# Rebuild Pydantic models to resolve forward references
# Import dependencies for model rebuilding
def _rebuild_models_when_ready():
    try:
        # Rebuild models now that imports are available
        Account.model_rebuild()
    except ImportError:
        pass  # Will be rebuilt later

_rebuild_models_when_ready()
