# This file is auto-generated by the CDP protocol generator.
# Do not edit this file manually as your changes will be overwritten.
# Generated from Chrome DevTools Protocol specifications.

"""CDP WebAuthn Domain Types"""

from enum import Enum
from pydantic import BaseModel
from typing import Optional

AuthenticatorId = str



class AuthenticatorProtocol(Enum):
    U2F = "u2f"
    CTAP2 = "ctap2"



class Ctap2Version(Enum):
    CTAP2_0 = "ctap2_0"
    CTAP2_1 = "ctap2_1"



class AuthenticatorTransport(Enum):
    USB = "usb"
    NFC = "nfc"
    BLE = "ble"
    CABLE = "cable"
    INTERNAL = "internal"



class VirtualAuthenticatorOptions(BaseModel):
    protocol: "AuthenticatorProtocol"
    transport: "AuthenticatorTransport"
    ctap2Version: "Optional[Ctap2Version]" = None
    hasResidentKey: "Optional[bool]" = None
    hasUserVerification: "Optional[bool]" = None
    hasLargeBlob: "Optional[bool]" = None
    hasCredBlob: "Optional[bool]" = None
    hasMinPinLength: "Optional[bool]" = None
    hasPrf: "Optional[bool]" = None
    automaticPresenceSimulation: "Optional[bool]" = None
    isUserVerified: "Optional[bool]" = None
    defaultBackupEligibility: "Optional[bool]" = None
    defaultBackupState: "Optional[bool]" = None



class Credential(BaseModel):
    credentialId: "str"
    isResidentCredential: "bool"
    privateKey: "str"
    signCount: "int"
    rpId: "Optional[str]" = None
    userHandle: "Optional[str]" = None
    largeBlob: "Optional[str]" = None
    backupEligibility: "Optional[bool]" = None
    backupState: "Optional[bool]" = None
    userName: "Optional[str]" = None
    userDisplayName: "Optional[str]" = None


# Rebuild Pydantic models to resolve forward references
# Import dependencies for model rebuilding
def _rebuild_models_when_ready():
    try:
        # Rebuild models now that imports are available
        VirtualAuthenticatorOptions.model_rebuild()
        Credential.model_rebuild()
    except ImportError:
        pass  # Will be rebuilt later

_rebuild_models_when_ready()
